version: '3.1'
services:
  rmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - '15672:15672'
      - '5672:5672'
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./dbdata:/data/db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=root
